language: go
go:
- master
deploy:
  provider: heroku
  api_key:
    secure: Z49q0l9n4onFkPUer7ax1ItJzGlkMdevEAmGxJBaXP4wXpcHDzk6yWh1gALvToSIc7US+Nex9ZhYWlItuaMpsMwrR+ZN1YYlgDJp6QQPEoaOzpZ7aNXznohxhi/5LE71UsswS91aBWepWTGeNpeSbzuIX/q69bQpb8PHuuQt4saDagiB5WD11yPRF3oDSSEbvtVmvSgLuf/OYPz3za7ejCuBzm+fEtZaKNJ0Zq9iAzF/Y3p6DOMc0hh3a1x0jrjMF7WxlU1s7GWkue3qE73YBFU6JDpusDDLqCxM0c5Pi0iInnUqpsc2MjQGNWraPGo1Fzb4KOiy6aXdxug9uTImdr0xExMsiO+q9w2nzzNPdHJ3MrUBxuHG8mGhOaS6rtCqGM6XUuDhl2c62RFmofdmcHeQr3h8NkZuqfMDSs35qThGymwEVr5yh6exgTxI2WeOSK5jdLZev+kNc2+pP8taMrrb/R4kM491QAXbHMxebPq+GJA7fHx3acEGIjSe78yEChVKBP77uAZXop17TIn4MVSwnJ6WfWLxhFuqDHc35k59mjtzclPw8HtUppPpT5CKlqwp4JyeopCmQCC89ZQvRltVRNd3zG1bIRBctuUEzZrja9JCWYhQhzuEluOk8LKkMTRY3+BIz45Dd/CsHNkFbuSGNMoKgR8EkOPBp5JMAhg=
  app: messaging-server4
  on:
    branch: main
    repo: geomin76/messaging-server
